version: '3.9'

services:
  db:
    container_name: db
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    networks:
      - nginx-network

  backend:
    container_name: backend
    build:
      context: ./backend # context tells us where to look for the Dockerfile
    command: /scripts/start_dev.sh
    volumes:
      - ./backend:/code
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
    networks:
      - nginx-network
    depends_on:
      - db

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app/:ro
      # mounting the frontend directory from our local machine into /app. ro specifies the mounted volume is read-only
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
      - db
    networks:
      - nginx-network
    environment:
      - NODE_ENV=development

  nginx:
    image: nginx:alpine
    container_name: nginx
    # map port 8000 on our local machine to port 80 of this container
    ports:
      - "8000:80"
    depends_on:
      - backend
    volumes:
      - ./nginx/dev.conf:/etc/nginx/nginx.conf:ro
    networks:
      - nginx-network


volumes:
  postgres_data:

networks:
  nginx-network:
    driver: bridge