version: '3.9'

services:
  db:
    container_name: db
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    networks:
      - backend-network

  backend:
    container_name: backend
    build:
      context: ./backend # context tells us where to look for the Dockerfile
    command: /scripts/start_prod.sh
    volumes:
      - ./backend:/code
      - django_static:/backend/static
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
    networks:
      - nginx-network
    depends_on:
      - db

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app/:ro
      # mounting the frontend directory from our local machine into /app. ro specifies the mounted volume is read-only
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=db
    networks:
      - nginx-network
    depends_on:
      - backend
      - db

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./nginx/prod.conf:/was/etc/nginx/nginx.conf:ro
      # When a request that starts with /static comes in, we route it to /usr/src/app/static instead of having Django process the request
      - django_static:/usr/src/app/static
    networks:
      - nginx-network
      - backend-network
    depends_on:
      - backend


volumes:
  postgres_data:
  django_static:


networks:
  nginx-network:
    driver: bridge
  backend-network:
    driver: bridge